username: admin #账户名
password:  #密码 比翼平台可不用填密码
tokenRedisKey: "ctsi:token" #存储token 的redis key 名称
redisHost: localhost #redis 地址
redisPort: 6379 #redis 端口
redisPassword: "" #redis 密码
redisDatabase: 0 #redis 库

refushTokenTime: 300 #刷新token时间，单位秒，默认5分钟